# Generated by Django 4.2.10 on 2025-02-11 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RedirectRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('redirect_url', models.CharField(max_length=450)),
                ('is_private', models.BooleanField(default=False)),
                ('redirect_identifier', models.CharField(editable=False, max_length=16, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirect_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'redirect_rules',
            },
        ),
    ]
